# Generated by Django 3.2.9 on 2021-11-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oder',
            old_name='inventory',
            new_name='total_product',
        ),
    ]
