# Generated by Django 3.2.9 on 2021-11-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_rename_inventory_oder_total_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='describes',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
